apiVersion: apps/v1
kind: Deployment
metadata:
  name: gha-nodeapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gha-nodeapp
  template:
    metadata:
      labels:
        app: gha-nodeapp
    spec:
      containers:
        - name: gha-nodeapp
          image: natesan750/gha-nodeapp:1351dd0
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
