apiVersion: v1
kind: Service
metadata:
  name: gha-nodeapp-service
  namespace: default
spec:
  selector:
    app: gha-nodeapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer