name: kubernetes CI
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  nodeapp-ci:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push docker image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker build -t natesan750/gha-nodeapp:$SHORT_SHA .
          docker push natesan750/gha-nodeapp:$SHORT_SHA

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update deployment.yml with new image tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          yq e '.spec.template.spec.containers[0].image = "natesan750/gha-nodeapp:'"$SHORT_SHA"'"' -i k8s/deployment.yml

      - name: Commit and push updated deployment.yml
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add k8s/deployment.yml
          git commit -m "Update image tag to $SHORT_SHA"
          git push

    

          
        
     
